#!/bin/bash
# StackCodeSy Content Security Policy and HTTP Security Headers Configuration
# This script generates nginx configuration for security headers

set -e

ENABLE_CSP="${STACKCODESY_ENABLE_CSP:-true}"
CSP_POLICY="${STACKCODESY_CSP_POLICY:-default}"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() {
    echo -e "${GREEN}[StackCodeSy CSP]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[StackCodeSy CSP]${NC} $1"
}

# Create nginx security headers configuration
create_nginx_security_config() {
    local NGINX_CONFIG_DIR="/etc/nginx/conf.d"
    local SECURITY_CONF="$NGINX_CONFIG_DIR/stackcodesy-security-headers.conf"

    mkdir -p "$NGINX_CONFIG_DIR"

    log_info "Creating nginx security headers configuration..."

    # Determine CSP policy
    local CSP_HEADER=""
    case "$CSP_POLICY" in
        "strict")
            CSP_HEADER="default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self';"
            ;;
        "moderate")
            CSP_HEADER="default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:; frame-ancestors 'self'; base-uri 'self';"
            ;;
        "relaxed"|"default"|*)
            CSP_HEADER="default-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src 'self' data: https:; font-src 'self' data: https:; connect-src 'self' https: wss:; frame-ancestors 'self';"
            ;;
    esac

    cat > "$SECURITY_CONF" << NGINX_EOF
# StackCodeSy Security Headers Configuration
# Generated by configure-csp.sh

# Content Security Policy
add_header Content-Security-Policy "$CSP_HEADER" always;

# Prevent clickjacking attacks
add_header X-Frame-Options "SAMEORIGIN" always;

# Prevent MIME type sniffing
add_header X-Content-Type-Options "nosniff" always;

# Enable XSS protection
add_header X-XSS-Protection "1; mode=block" always;

# Control referrer information
add_header Referrer-Policy "strict-origin-when-cross-origin" always;

# HSTS - Force HTTPS (uncomment if using HTTPS)
# add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

# Permissions Policy (formerly Feature Policy)
add_header Permissions-Policy "geolocation=(), microphone=(), camera=(), payment=(), usb=(), magnetometer=(), gyroscope=(), accelerometer=()" always;

# Remove server signature
server_tokens off;

# Additional security headers
add_header X-Permitted-Cross-Domain-Policies "none" always;
add_header Cross-Origin-Embedder-Policy "require-corp" always;
add_header Cross-Origin-Opener-Policy "same-origin" always;
add_header Cross-Origin-Resource-Policy "same-origin" always;
NGINX_EOF

    log_info "Nginx security headers configuration created: $SECURITY_CONF"
}

# Create standalone nginx reverse proxy configuration
create_nginx_reverse_proxy() {
    local NGINX_SITE="/etc/nginx/sites-available/stackcodesy"

    cat > "$NGINX_SITE" << 'NGINX_SITE_EOF'
# StackCodeSy Nginx Reverse Proxy Configuration
# This file should be symlinked to /etc/nginx/sites-enabled/

upstream stackcodesy_backend {
    server 127.0.0.1:8080;
    keepalive 64;
}

# Rate limiting zones
limit_req_zone $binary_remote_addr zone=stackcodesy_general:10m rate=10r/s;
limit_req_zone $binary_remote_addr zone=stackcodesy_api:10m rate=30r/s;
limit_conn_zone $binary_remote_addr zone=stackcodesy_conn:10m;

server {
    listen 80;
    server_name _;

    # Maximum body size
    client_max_body_size 50M;
    client_body_timeout 60s;
    client_header_timeout 60s;

    # Rate limiting
    limit_req zone=stackcodesy_general burst=20 nodelay;
    limit_conn stackcodesy_conn 10;

    # Security headers (include the generated config)
    include /etc/nginx/conf.d/stackcodesy-security-headers.conf;

    # Logging
    access_log /var/log/nginx/stackcodesy-access.log combined;
    error_log /var/log/nginx/stackcodesy-error.log warn;

    # Proxy to StackCodeSy
    location / {
        proxy_pass http://stackcodesy_backend;
        proxy_http_version 1.1;

        # WebSocket support
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Standard proxy headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 300s;

        # Buffering
        proxy_buffering off;
        proxy_request_buffering off;
    }

    # API endpoints with higher rate limits
    location /api/ {
        limit_req zone=stackcodesy_api burst=50 nodelay;

        proxy_pass http://stackcodesy_backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Health check endpoint (no rate limiting)
    location /health {
        proxy_pass http://stackcodesy_backend;
        access_log off;
    }

    # Block access to sensitive files
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }

    location ~ \.(env|git|svn|htaccess|htpasswd)$ {
        deny all;
        access_log off;
        log_not_found off;
    }
}
NGINX_SITE_EOF

    log_info "Nginx reverse proxy configuration created: $NGINX_SITE"
    log_info "Enable with: ln -s $NGINX_SITE /etc/nginx/sites-enabled/"
}

# Create docker-compose nginx service
create_docker_nginx_config() {
    local DOCKER_NGINX_YML="/stackcodesy/docker-compose.nginx.yml"

    cat > "$DOCKER_NGINX_YML" << 'DOCKER_NGINX_EOF'
version: '3.8'

# This file extends docker-compose.yml to add nginx reverse proxy
# Usage: docker-compose -f docker-compose.yml -f docker-compose.nginx.yml up

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./security/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./security/stackcodesy-site.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx-logs:/var/log/nginx
    depends_on:
      - stackcodesy
    networks:
      - stackcodesy-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  stackcodesy:
    # Remove port exposure since nginx will handle it
    ports: []
    expose:
      - "8080"

volumes:
  nginx-logs:
    driver: local
DOCKER_NGINX_EOF

    log_info "Docker nginx configuration created: $DOCKER_NGINX_YML"
}

# Create security headers validation script
create_header_validator() {
    cat > /usr/local/bin/validate-security-headers.sh << 'VALIDATOR_EOF'
#!/bin/bash
# Validates that security headers are properly configured

URL="${1:-http://localhost:8080}"

echo "Checking security headers for: $URL"
echo "=========================================="

HEADERS=$(curl -sI "$URL" 2>/dev/null)

check_header() {
    local header_name="$1"
    if echo "$HEADERS" | grep -qi "^$header_name:"; then
        echo "✓ $header_name: $(echo "$HEADERS" | grep -i "^$header_name:" | cut -d: -f2- | xargs)"
    else
        echo "✗ $header_name: MISSING"
    fi
}

check_header "Content-Security-Policy"
check_header "X-Frame-Options"
check_header "X-Content-Type-Options"
check_header "X-XSS-Protection"
check_header "Referrer-Policy"
check_header "Strict-Transport-Security"
check_header "Permissions-Policy"

echo "=========================================="
VALIDATOR_EOF

    chmod +x /usr/local/bin/validate-security-headers.sh
    log_info "Security headers validator created: /usr/local/bin/validate-security-headers.sh"
}

# Main execution
if [ "$ENABLE_CSP" != "true" ]; then
    log_warning "Content Security Policy is DISABLED"
    exit 0
fi

log_info "Configuring Content Security Policy and security headers..."
log_info "CSP Policy Level: $CSP_POLICY"

create_nginx_security_config
create_nginx_reverse_proxy
create_docker_nginx_config
create_header_validator

log_info "CSP and security headers configuration complete"
echo ""
echo "Configuration files created:"
echo "  - Nginx security headers: /etc/nginx/conf.d/stackcodesy-security-headers.conf"
echo "  - Nginx site config: /etc/nginx/sites-available/stackcodesy"
echo "  - Docker compose nginx: /stackcodesy/docker-compose.nginx.yml"
echo ""
echo "To use with Docker:"
echo "  docker-compose -f docker-compose.yml -f docker-compose.nginx.yml up"
echo ""
echo "To validate headers:"
echo "  /usr/local/bin/validate-security-headers.sh http://localhost"
echo ""

exit 0
